const names = [
    "Alfie",
    "Angel",
    "Argus",
    "Arwen",
    "Ashton",
    "Baby",
    "Bailey",
    "Bassil",
    "Beage",
    "Bender",
    "Benny",
    "Big Red",
    "Big Sammy",
    "Binka",
    "Binx",
    "Blackie",
    "Bobo",
    "Boogie",
    "Boris",
    "Bowser",
    "Brandy",
    "Buddy",
    "Butterscotch",
    "Cally",
    "Caramel",
    "Casey",
    "Catherine",
    "Cece",
    "Celine",
    "Cherio",
    "Chloe",
    "Churchill",
    "Cinders",
    "Clarence",
    "Claude",
    "Cleo",
    "Coffee",
    "Cookie",
    "Cooper",
    "Cosmo",
    "Couch Potato",
    "Daisy",
    "Dakota",
    "Dark Moon",
    "David",
    "Denver",
    "Diesel",
    "Dilon",
    "Disney",
    "Dissy",
    "Divine",
    "Dude",
    "Ebony",
    "Enzo",
    "Faggie",
    "Fagison",
    "Felix",
    "Ferris",
    "Fifi",
    "Flowerbee",
    "Fluffernet",
    "Fluffy",
    "Fosters",
    "Freckles",
    "Frollo",
    "Freckuls",
    "Fudge",
    "Fudge",
    "Fuffie",
    "Gabrielle",
    "Gadget",
    "Gary",
    "Ginger",
    "Gipsy",
    "Gizmo",
    "Gore",
    "Grace",
    "Griswald",
    "Grizz",
    "Grizzabella",
    "Harley",
    "Hazel",
    "Henry",
    "Hex",
    "Hoppy",
    "Indy",
    "Izzy",
    "Jasmine",
    "Jay",
    "Jinx",
    "Jon",
    "Jymes Dean",
    "Katie",
    "Kelee",
    "Kenny",
    "Kirby",
    "Kitty",
    "Kliff",
    "Kool Kat",
    "Lady",
    "Larry",
    "Lera",
    "Lexie",
    "Lincoln",
    "Little",
    "Lucy",
    "Mac",
    "Mackie",
    "Marbles",
    "Mario",
    "Marley",
    "Marmelade",
    "Martin",
    "Max",
    "Maxine",
    "Merlin",
    "Micky",
    "Midnight",
    "Mippen",
    "Misty",
    "Missy",
    "Mittens",
    "Mitzy",
    "Molly",
    "Moon Pie",
    "Moriarty",
    "Moritz",
    "Moses",
    "Mozart",
    "Ms Kitty",
    "Myah",
    "Nala",
    "Natasha",
    "Nemo",
    "Niglet",
    "Nikita",
    "Noodles",
    "Noodlehead",
    "Oliver",
    "Oreo",
    "Orwell",
    "Oscar",
    "Panda",
    "Patsy",
    "Paws",
    "Peanut",
    "Peter",
    "Phoebe",
    "Pinkle",
    "Plinky",
    "Poocat",
    "Pooder",
    "Pookie",
    "Prince",
    "Princess",
    "Pumpkin",
    "Punkin",
    "Purr",
    "Rajha",
    "Ralph",
    "Rascal",
    "Romeo",
    "Roxie",
    "Rylie",
    "Sadie",
    "Salem",
    "Sammy",
    "Sasha",
    "Scooter",
    "Scout",
    "Secret",
    "Shadow",
    "Shane",
    "Shelby",
    "Simba",
    "Simon",
    "Simpson",
    "Slippers",
    "Smudge",
    "Sophie",
    "Soushi",
    "Sparkle",
    "Sputnick",
    "Stanley",
    "Starlett",
    "Sticky",
    "Stimpy",
    "Stray",
    "Sugar",
    "Sunny",
    "Tater",
    "Tigger",
    "Tinkerbell",
    "Tina",
    "Tiny",
    "Tobi",
    "Tori",
    "Tricia",
    "Tucker",
    "Tuna",
    "Twiggy",
    "Walter",
    "Whiskers",
    "Willow",
    "Wyatt",
    "Xman",
    "Zakkie",
    "Zebra"
];

const descriptions = [
    "This cutie's ears have a solid AAA rating from the international cat authority.",
    "Fun fact: this cool kitten can sense food from more than two houses away.",
    "Look deep into the eyes of this cat for just a minute, and you may come away knowing the secrets of the universe.",
    "Despite any claims to the contrary, this little buddy has an absolute monopoly on the softest fur in the county.",
    "What a gorgeous kitten!!!!!!",
    "Could you seriously decide *not* to take this cat home and give them a better life? We think not!",
    "On a cuteness rating from 1 to 10, this cat broke all measurement devices and severely wounded a team of physicists.",
    "Just imagine coming home to this warm little loaf of cat waiting to share its day.",
    "What? You'll take this one? Too bad, too late -- this cat is spoken for!!!",
    "The one fluffy kitteh to Rule Them All!",
    "Don't let this cutie near too much cat nip -- you might never get them to relax again!",
    "Have you ever seen a feline friend with such a look? It's cats like this that make dogs cry.",
    "THIS CAT NOT SAFE FOR THE FAINT OF HEART (because it's so adorable)",
    "This cat? Priceless. For everything else, there's kitten yarn.",
    "You want the floof? You can't handle the floof!",
    "Meow meow meow, meow meow meow, wherefore art thou, meow meow meow?",
    "This cat inspired a famous song: To every kitten, turn, turn, turn, there is a cutie -- turn, turn, turn.",
    "This cat is just a great little friend and deserves a good home. Come on. Why not help them out?",
    "Only YOU can prevent Forest Fires -- or alternatively, adopt this cat!",
    "Top Cat Award, 2015-2018",
    "This cat intentionally left blank",
    "When should you adopt, you ask? There's no cat like the present!",
    "Don't worry whether there's an app for that -- because right here you have a cat for that!",
    "This cat has had a great time learning and finding themselves through 2018 and is ready to put down some roots and really get in touch with a place.",
    "Soon.",
    "No cat? No problem! This one's for you, friend!",
    "A professor emeritus of yarn law at Cat Yale",
    "This cat is famous, but don't worry, you wouldn't recognize where it's famous from.",
    "The Author, pictured at their summer home in Vermont",
    "Kim Kardashian claims to this dayto have taken this picture. The cat has not cared to comment",
    "A major breakthrough in cat-O-vision!",
    "Wait... what's that in its paw!!?",
    "When you see it...",
    "Never has a cat such as this been so ready for adoption. Come in today!",
    "'Cats! The musical' was largely based on this cat's life. And to a lesser degree the works of T. S. Eliot",
    "If this were your cat, you'd be home by now!",
    "Be careful: in the games of life and of love, this cat plays for keeps. For keeps!",
    "This is not a cat.",
    "Once, twice, three times a kitty!",
    "Too late. Cat taken.",
    "This cat is the Queen of the Strings",
    "This cat was actually World Vision's first choice over Sarah McLachlan, but was unavailable due to scheduling conflicts.",
    "You get a cat! And you get a cat! Everyone here, tonight you're all taking home a brand new KITTEN!",
    "The best friend ever.",
    "Very cute. A 'fluff said.",
    "I'll make it easy for you: just adopt this one."
];

export { names, descriptions };
